CREATE TABLE visitante (ID INTEGER PRIMARY KEY AUTOINCREMENT, NumVisitante INTEGER NOT NULL);
CREATE TABLE aluno(ID INTEGER PRIMARY KEY AUTOINCREMENT, NumAluno INTEGER NOT NULL);
CREATE TABLE sala(ID INTEGER PRIMARY KEY AUTOINCREMENT, Bloco INTEGER NOT NULL, Piso INTEGER NOT NULL, Numero INTEGER NOT NULL, LotacaoMax INTEGER);
CREATE TABLE professor(ID INTEGER PRIMARY KEY AUTOINCREMENT, NumProfessor INTEGER NOT NULL);
CREATE TABLE disciplina(ID INTEGER PRIMARY KEY AUTOINCREMENT, Codigo INTEGER, Designacao TEXT, Creditos INTEGER NOT NULL, Regente INTEGER);
CREATE TABLE turma(ID INTEGER PRIMARY KEY AUTOINCREMENT, NInscritos INTEGER, MaxInscritos INTEGER, Tipo TEXT, IDDisciplina INTEGER, NumProf INTEGER);
CREATE TABLE aula(ID INTEGER PRIMARY KEY AUTOINCREMENT, HoraInicio TEXT, HoraFinal TEXT, IDSala INTEGER, IDTurma INTEGER);
CREATE TABLE turmaaluno(ID INTEGER PRIMARY KEY AUTOINCREMENT, NumAluno INTEGER, IDTurma INTEGER);
CREATE TABLE acessos(ID INTEGER PRIMARY KEY AUTOINCREMENT, IDSala INTEGER, HoraEntrada TEXT, HoraSaida TEXT, NumAluno INTEGER, NumVisitante INTEGER);