language: node_js
node_js:
  - "9.2.0"

branches:
  only:
    - frontEnd-Deploy

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod

# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
