sudo: required
language: php

branches:
  only:
    - backEnd-Deploy

services:
  - docker

before_script:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
script:
  - docker build -t cafcul-backend-api .
  - docker tag cafcul-backend-api:latest 365892155626.dkr.ecr.eu-west-1.amazonaws.com/cafcul-backend-api:latest
  - docker push 365892155626.dkr.ecr.eu-west-1.amazonaws.com/cafcul-backend-api:latest