version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: cafcul-backend-api
    ports:
      - 80:80
    network_mode: "bridge"
    extra_hosts:
      - "cafculdatabase:db.cafcul.hugocurado.info"