version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: cafcul-backend-api
    ports:
      - 8080:80
    network_mode: "bridge"
    extra_hosts:
      - "cafculdatabase:160.153.128.44"