INSERT INTO disciplina(id,designacao, prof_t) VALUES (1,'Elementos de Matematica I',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (2,'Elementos de Matematica II',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (3,'Fisica I',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (4,'Fisica II',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (5,'Programação I',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (6,'Programação II',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (7,'Sistemas Operativos',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (8,'Aplicações Distribuidas',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (9,'Conceção de Produto',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (10,'Analise e Desenho de Software',45000);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (11,'Testes de Software I',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (12,'Testes de Software II',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (13,'IoT I',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (14,'IoT II',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (15,'Projeto de Tecnologias de Informação',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (16,'Projecto de Tecnologias de Redes',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (17,'Segurança Informática',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (18,'Estatistica I',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (19,'Estatistica II',45004);
INSERT INTO disciplina(id,designacao, prof_t) VALUES (20,'Redes de Computadores',45004);
