CREATE TABLE Aluno (ID int PRIMARY KEY, NumAluno int UNIQUE NOT NULL, PrimeiroNome varchar(255), UltimoNome varchar(255));
CREATE TABLE Sala (ID int PRIMARY KEY, Bloco int, Piso int, Numero int, LotacaoMax int);
CREATE TABLE Professor (ID int PRIMARY KEY, NumProfessor int UNIQUE NOT NULL, PrimeiroNome varchar(255), UltimoNome varchar(255));
CREATE TABLE Disciplina (ID int PRIMARY KEY, Codigo int UNIQUE, Designacao varchar(255) UNIQUE, Creditos int NOT NULL, Regente int, FOREIGN KEY (Regente) REFERENCES Professor(ID));
CREATE TABLE Turma (ID int PRIMARY KEY, NInscritos int, MaxInscritos int, Tipo varchar(2), IDDisciplina int, IDProf int, FOREIGN KEY (IDDisciplina) REFERENCES Disciplina(ID), FOREIGN KEY (IDProf) REFERENCES Professor(ID));
CREATE TABLE Aula (ID int PRIMARY KEY, HoraInicio datetime, HoraFrom datetime, IDSala int, IDTurma int, FOREIGN KEY (IDSala) REFERENCES Sala(ID), FOREIGN KEY (IDTurma) REFERENCES Turma(ID));
CREATE TABLE TurmaAluno (ID int PRIMARY KEY, IDAluno int, IDTurma int, FOREIGN KEY (IDAluno) REFERENCES Aluno(ID), FOREIGN KEY (IDTurma) REFERENCES Turma(ID));
CREATE TABLE Semana1 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana2 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana3 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana4 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana5 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana6 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana7 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana8 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana9 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana10 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana11 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana12 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana13 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana14 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
CREATE TABLE Semana15 (ID int PRIMARY KEY, Dia int, IDSala int, IDAluno int, FOREIGN KEY (IDSala) REFERENCES Sala(ID),FOREIGN KEY (IDAluno) REFERENCES Aluno(ID));
