INSERT INTO disciplina(designacao, prof_t) VALUES ('Elementos de Matematica I',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Elementos de Matematica II',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Fisica I',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Fisica II',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Programação I',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Programação II',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Sistemas Operativos',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Aplicações Distribuidas',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Conceção de Produto',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Analise e Desenho de Software',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Testes de Software I',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Testes de Software II',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('IoT I',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('IoT II',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Projeto de Tecnologias de Informação',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Projecto de Tecnologias de Redes',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Segurança Informática',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Estatistica I',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Estatistica II',45004);
INSERT INTO disciplina(designacao, prof_t) VALUES ('Redes de Computadores',45004);
