INSERT INTO presencas(aula,aluno) VALUES (1000,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1000;
INSERT INTO presencas(aula,aluno) VALUES (1000,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1000;
INSERT INTO presencas(aula,aluno) VALUES (1000,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1000;
INSERT INTO presencas(aula,aluno) VALUES (1000,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1000;
INSERT INTO presencas(aula,aluno) VALUES (1000,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1000;
INSERT INTO presencas(aula,aluno) VALUES (1000,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1000;
INSERT INTO presencas(aula,aluno) VALUES (1001,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1001;
INSERT INTO presencas(aula,aluno) VALUES (1001,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1001;
INSERT INTO presencas(aula,aluno) VALUES (1001,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1001;
INSERT INTO presencas(aula,aluno) VALUES (1001,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1001;
INSERT INTO presencas(aula,aluno) VALUES (1001,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1001;
INSERT INTO presencas(aula,aluno) VALUES (1001,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1001;
INSERT INTO presencas(aula,aluno) VALUES (1002,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1002;
INSERT INTO presencas(aula,aluno) VALUES (1002,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1002;
INSERT INTO presencas(aula,aluno) VALUES (1002,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1002;
INSERT INTO presencas(aula,aluno) VALUES (1002,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1002;
INSERT INTO presencas(aula,aluno) VALUES (1002,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1002;
INSERT INTO presencas(aula,aluno) VALUES (1002,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1002;
INSERT INTO presencas(aula,aluno) VALUES (1003,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1003;
INSERT INTO presencas(aula,aluno) VALUES (1003,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1003;
INSERT INTO presencas(aula,aluno) VALUES (1003,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1003;
INSERT INTO presencas(aula,aluno) VALUES (1003,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1003;
INSERT INTO presencas(aula,aluno) VALUES (1003,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1003;
INSERT INTO presencas(aula,aluno) VALUES (1003,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1003;
INSERT INTO presencas(aula,aluno) VALUES (1004,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1004;
INSERT INTO presencas(aula,aluno) VALUES (1004,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1004;
INSERT INTO presencas(aula,aluno) VALUES (1004,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1004;
INSERT INTO presencas(aula,aluno) VALUES (1004,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1004;
INSERT INTO presencas(aula,aluno) VALUES (1004,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1004;
INSERT INTO presencas(aula,aluno) VALUES (1004,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1004;
INSERT INTO presencas(aula,aluno) VALUES (1005,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1005;
INSERT INTO presencas(aula,aluno) VALUES (1005,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1005;
INSERT INTO presencas(aula,aluno) VALUES (1005,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1005;
INSERT INTO presencas(aula,aluno) VALUES (1005,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1005;
INSERT INTO presencas(aula,aluno) VALUES (1005,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1005;
INSERT INTO presencas(aula,aluno) VALUES (1005,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1005;
INSERT INTO presencas(aula,aluno) VALUES (1006,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1006;
INSERT INTO presencas(aula,aluno) VALUES (1006,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1006;
INSERT INTO presencas(aula,aluno) VALUES (1006,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1006;
INSERT INTO presencas(aula,aluno) VALUES (1006,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1006;
INSERT INTO presencas(aula,aluno) VALUES (1006,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1006;
INSERT INTO presencas(aula,aluno) VALUES (1006,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1006;
INSERT INTO presencas(aula,aluno) VALUES (1007,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1007;
INSERT INTO presencas(aula,aluno) VALUES (1007,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1007;
INSERT INTO presencas(aula,aluno) VALUES (1007,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1007;
INSERT INTO presencas(aula,aluno) VALUES (1007,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1007;
INSERT INTO presencas(aula,aluno) VALUES (1007,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1007;
INSERT INTO presencas(aula,aluno) VALUES (1007,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1007;
INSERT INTO presencas(aula,aluno) VALUES (1008,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1008;
INSERT INTO presencas(aula,aluno) VALUES (1008,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1008;
INSERT INTO presencas(aula,aluno) VALUES (1008,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1008;
INSERT INTO presencas(aula,aluno) VALUES (1008,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1008;
INSERT INTO presencas(aula,aluno) VALUES (1008,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1008;
INSERT INTO presencas(aula,aluno) VALUES (1008,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1008;
INSERT INTO presencas(aula,aluno) VALUES (1009,45000);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45000 FROM aula a WHERE a.id=1009;
INSERT INTO presencas(aula,aluno) VALUES (1009,45001);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45001 FROM aula a WHERE a.id=1009;
INSERT INTO presencas(aula,aluno) VALUES (1009,45002);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45002 FROM aula a WHERE a.id=1009;
INSERT INTO presencas(aula,aluno) VALUES (1009,45003);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45003 FROM aula a WHERE a.id=1009;
INSERT INTO presencas(aula,aluno) VALUES (1009,45004);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45004 FROM aula a WHERE a.id=1009;
INSERT INTO presencas(aula,aluno) VALUES (1009,45005);
INSERT INTO acesso(data_entrada,data_fim,espaco,user) SELECT a.data_inicio, a.data_fim, a.espaco, 45005 FROM aula a WHERE a.id=1009;
